<?php

use Illuminate\Database\Seeder;

class UsersTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('users')->insert([
            [
            'first_name' => 'Дмитрий',
            'last_name' => 'Иванов',
            'nickname' => 'Якудза',
            'email' => 'admin@admin.by',
            'password' => Hash::make('3121985'),
            'avatar' => 'avatars/1/8SJDx5YKdQ60z36Ce6qteDAkeYTFBZBt76MYTWDC.jpeg',
            'verified' => true,
            'remember_token' => str_random(50),
            'created_at' => now(),
            'updated_at' => now(),
            ],
            [
                'first_name' => 'Иван',
                'last_name' => 'Петров',
                'nickname' => 'Самурай',
                'email' => 'admin1@admin.by',
                'password' => Hash::make('3121985'),
                'avatar' => 'avatars/1/8SJDx5YKdQ60z36Ce6qteDAkeYTFBZBt76MYTWDC.jpeg',
                'verified' => true,
                'remember_token' => str_random(50),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'first_name' => 'Сидор',
                'last_name' => 'Сидоров',
                'nickname' => 'Князь',
                'email' => 'admin2@admin.by',
                'password' => Hash::make('3121985'),
                'avatar' => 'avatars/1/8SJDx5YKdQ60z36Ce6qteDAkeYTFBZBt76MYTWDC.jpeg',
                'verified' => true,
                'remember_token' => str_random(50),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'first_name' => 'Александр',
                'last_name' => 'Дмитриев',
                'nickname' => 'Сёгун',
                'email' => 'admin3@admin.by',
                'password' => Hash::make('3121985'),
                'avatar' => 'avatars/1/8SJDx5YKdQ60z36Ce6qteDAkeYTFBZBt76MYTWDC.jpeg',
                'verified' => true,
                'remember_token' => str_random(50),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'first_name' => 'Пётр',
                'last_name' => 'Адександров',
                'nickname' => 'Япошка',
                'email' => 'admin4@admin.by',
                'password' => Hash::make('3121985'),
                'avatar' => 'avatars/1/8SJDx5YKdQ60z36Ce6qteDAkeYTFBZBt76MYTWDC.jpeg',
                'verified' => true,
                'remember_token' => str_random(50),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'first_name' => 'Дмитрий',
                'last_name' => 'Андреев',
                'nickname' => 'Император',
                'email' => 'admin5@admin.by',
                'password' => Hash::make('3121985'),
                'avatar' => 'avatars/1/8SJDx5YKdQ60z36Ce6qteDAkeYTFBZBt76MYTWDC.jpeg',
                'verified' => true,
                'remember_token' => str_random(50),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'first_name' => 'Андрей',
                'last_name' => 'Дмитриев',
                'nickname' => 'Анимешник',
                'email' => 'admin6@admin.by',
                'password' => Hash::make('3121985'),
                'avatar' => 'avatars/1/8SJDx5YKdQ60z36Ce6qteDAkeYTFBZBt76MYTWDC.jpeg',
                'verified' => true,
                'remember_token' => str_random(50),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'first_name' => 'Александр',
                'last_name' => 'Сидоров',
                'nickname' => 'Воин',
                'email' => 'admin7@admin.by',
                'password' => Hash::make('3121985'),
                'avatar' => 'avatars/1/8SJDx5YKdQ60z36Ce6qteDAkeYTFBZBt76MYTWDC.jpeg',
                'verified' => true,
                'remember_token' => str_random(50),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'first_name' => 'Дмитрий',
                'last_name' => 'Фёдоров',
                'nickname' => 'Псих',
                'email' => 'admin8@admin.by',
                'password' => Hash::make('3121985'),
                'avatar' => 'avatars/1/8SJDx5YKdQ60z36Ce6qteDAkeYTFBZBt76MYTWDC.jpeg',
                'verified' => true,
                'remember_token' => str_random(50),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'first_name' => 'Фёдор',
                'last_name' => 'Иванов',
                'nickname' => 'Умница',
                'email' => 'admin9@admin.by',
                'password' => Hash::make('3121985'),
                'avatar' => 'avatars/1/8SJDx5YKdQ60z36Ce6qteDAkeYTFBZBt76MYTWDC.jpeg',
                'verified' => true,
                'remember_token' => str_random(50),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'first_name' => 'Иван',
                'last_name' => 'Сергеев',
                'nickname' => 'Норм',
                'email' => 'admin10@admin.by',
                'password' => Hash::make('3121985'),
                'avatar' => 'avatars/1/8SJDx5YKdQ60z36Ce6qteDAkeYTFBZBt76MYTWDC.jpeg',
                'verified' => true,
                'remember_token' => str_random(50),
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ]);
    }
}
