os:
  - linux

language: php

php:
  - '7.2'

sudo: required

dist: trusty

addons:
  chrome: stable

services:
  - mysql

before_install:
  - phpenv config-rm xdebug.ini || true
  - travis_retry composer self-update
  - mysql -e 'CREATE DATABASE homestead;'

install:
  - cp .env.travis .env
  - travis_retry composer install --no-interaction --prefer-dist --no-suggest

before_script:
  - php artisan key:generate
  - php artisan migrate
  - pear install pear/PHP_CodeSniffer
  - phpenv rehash
  - npm install npm@latest -g
  - npm install
  - npm run production
  - google-chrome-stable --headless --disable-gpu --remote-debugging-port=9222 http://localhost &
  - php artisan serve &

script:
  - vendor/bin/phpunit
  - php artisan dusk
  - phpcs
